// SchedulingEngine/DecisionExplainer.ts
//
// Every scheduling decision must produce an explanation — generated by
// the engine itself, never by the LLM. Turns raw DecisionLogEntry[] into
// the "Detected overloaded Monday. ↓ Moved... ↓ Confidence increased from
// 71% to 92%." replay format.

import { dayNameOf } from "./types";
import { DecisionLogEntry } from "./types";

const STEP_PREFIXES: Record<string, string> = {
  intake: "Reviewed",
  sort: "Ordered",
  "dependency-cycle": "Detected a dependency problem:",
  unplaceable: "Could not place:",
  overflow: "Overload unavoidable:",
  placed: "Placed",
  "overloaded-day": "Detected overloaded day:",
  move: "Moved",
  "residual-overload": "Still over capacity:",
  "no-action": "No action needed:",
};

export function buildNarrative(
  log: DecisionLogEntry[],
  confidenceBefore?: number,
  confidenceAfter?: number,
): string[] {
  const lines = log.map((entry) => {
    const prefix = STEP_PREFIXES[entry.step] ?? entry.step;
    return `${prefix} ${entry.detail}`;
  });

  if (confidenceBefore !== undefined && confidenceAfter !== undefined) {
    const direction =
      confidenceAfter > confidenceBefore
        ? "increased"
        : confidenceAfter < confidenceBefore
          ? "decreased"
          : "held steady at";
    lines.push(
      confidenceAfter === confidenceBefore
        ? `Confidence held steady at ${confidenceAfter}%.`
        : `Confidence ${direction} from ${confidenceBefore}% to ${confidenceAfter}%.`,
    );
  }

  return lines;
}

/** Friendly day-of-week label for a YYYY-MM-DD date, for narrative text. */
export function dayLabel(dateStr: string): string {
  return dayNameOf(dateStr);
}

/** Joins a narrative array into the "Step. ↓ Step. ↓ Step." replay string used in UI. */
export function joinReplay(narrative: string[]): string {
  return narrative.join("\n↓\n");
}
